"""Add budget fields

Revision ID: 703988658c71
Revises: 002
Create Date: 2026-06-03 16:44:37.423633

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '703988658c71'
down_revision: Union[str, None] = '002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roads', sa.Column('budget_released', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('roads', sa.Column('funding_agency', sa.String(), nullable=True))
    op.add_column('roads', sa.Column('source_document_id', sa.String(), nullable=True))
    op.add_column('roads', sa.Column('budget_last_updated', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('roads', 'budget_last_updated')
    op.drop_column('roads', 'source_document_id')
    op.drop_column('roads', 'funding_agency')
    op.drop_column('roads', 'budget_released')
    # ### end Alembic commands ###
