"""Add source verification fields

Revision ID: 72515463678d
Revises: dc64a58b1c31
Create Date: 2026-06-03 17:34:00.381438

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '72515463678d'
down_revision: Union[str, None] = 'dc64a58b1c31'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('complaints', sa.Column('source_name', sa.String(), nullable=True))
    op.add_column('complaints', sa.Column('source_url', sa.String(), nullable=True))
    op.add_column('complaints', sa.Column('source_retrieval_date', sa.Date(), nullable=True))
    op.add_column('complaints', sa.Column('source_confidence', sa.String(), nullable=True))
    op.add_column('roads', sa.Column('source_name', sa.String(), nullable=True))
    op.add_column('roads', sa.Column('source_retrieval_date', sa.Date(), nullable=True))
    op.add_column('roads', sa.Column('source_confidence', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('roads', 'source_confidence')
    op.drop_column('roads', 'source_retrieval_date')
    op.drop_column('roads', 'source_name')
    op.drop_column('complaints', 'source_confidence')
    op.drop_column('complaints', 'source_retrieval_date')
    op.drop_column('complaints', 'source_url')
    op.drop_column('complaints', 'source_name')
    # ### end Alembic commands ###
