"""Add complaint routing history and authority fields

Revision ID: a66e6ca93538
Revises: 703988658c71
Create Date: 2026-06-03 16:57:48.775664

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'a66e6ca93538'
down_revision: Union[str, None] = '703988658c71'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('complaint_routing_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('complaint_id', sa.UUID(), nullable=False),
    sa.Column('routed_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('authority_name', sa.String(length=255), nullable=True),
    sa.Column('designation', sa.String(length=255), nullable=True),
    sa.Column('department', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['complaint_id'], ['complaints.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('complaints', sa.Column('authority_name', sa.String(length=255), nullable=True))
    op.add_column('complaints', sa.Column('authority_designation', sa.String(length=255), nullable=True))
    op.add_column('complaints', sa.Column('authority_phone', sa.String(length=50), nullable=True))
    # SQLite workaround: skip alter_column for UUID
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # SQLite workaround: skip alter_column for UUID
    op.drop_column('complaints', 'authority_phone')
    op.drop_column('complaints', 'authority_designation')
    op.drop_column('complaints', 'authority_name')
    op.drop_table('complaint_routing_history')
    # ### end Alembic commands ###
