"""Add contractor fields

Revision ID: dc64a58b1c31
Revises: a66e6ca93538
Create Date: 2026-06-03 17:29:23.664380

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'dc64a58b1c31'
down_revision: Union[str, None] = 'a66e6ca93538'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roads', sa.Column('contractor_agency', sa.String(), nullable=True))
    op.add_column('roads', sa.Column('contract_value', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('roads', sa.Column('completion_date', sa.Date(), nullable=True))
    op.add_column('roads', sa.Column('maintenance_warranty_years', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('roads', 'maintenance_warranty_years')
    op.drop_column('roads', 'completion_date')
    op.drop_column('roads', 'contract_value')
    op.drop_column('roads', 'contractor_agency')
    # ### end Alembic commands ###
